### PR TITLE
Better handling refract elements

### LINKED ISSUE #17: TypeError: Object #<Object> has no method 'replace'
This shows up in logs:

```
error: [index] EXCEPTION_UNCAUGHT:  TypeError: Object #<Object> has no method 'replace' 
Nov 30 17:28:24 apiary app/web.1:   at Function.fixNewLines (/app/node_modules/@apiaryio/metamorphoses/lib/adapters/refract/helper.js:12:14) 
Nov 30 17:28:24 apiary app/web.1:   at baseWrapperValue (/app/node_modules/@apiaryio/metamorphoses/node_modules/lodash/index.js:2768:30) 
Nov 30 17:28:24 apiary app/web.1:   at LodashWrapper.wrapperValue (/app/node_modules/@apiaryio/metamorphoses/node_modules/lodash/index.js:6124:14) 
Nov 30 17:28:24 apiary app/web.1:   at Object.transformAst (/app/node_modules/@apiaryio/metamorphoses/lib/adapters/refract-adapter.js:15:64) 
Nov 30 17:28:24 apiary app/web.1:   at transformSuccessResponse (/app/lib/parser.coffee:227:25) 
Nov 30 17:28:24 apiary app/web.1:   at transformParsingServiceResponse (/app/lib/parser.coffee:199:17) 
Nov 30 17:28:24 apiary app/web.1:   at /app/lib/parser.coffee:83:7 
Nov 30 17:28:24 apiary app/web.1:   at fn (/app/node_modules/async/lib/async.js:741:34) 
Nov 30 17:28:24 apiary app/web.1:   at /app/node_modules/async/lib/async.js:1208:16 
Nov 30 17:28:24 apiary app/web.1:   at /app/node_modules/async/lib/async.js:166:37 
Nov 30 17:28:24 apiary app/web.1:   at /app/node_modules/async/lib/async.js:701:43 
Nov 30 17:28:24 apiary app/web.1:   at /app/node_modules/async/lib/async.js:167:37 
Nov 30 17:28:24 apiary app/web.1:   at /app/node_modules/async/lib/async.js:1204:30 
Nov 30 17:28:24 apiary app/web.1:   at Request._callback (/app/lib/parser.coffee:185:12) 
Nov 30 17:28:24 apiary app/web.1:   at Request.self.callback (/app/node_modules/request/request.js:198:22) 
Nov 30 17:28:24 apiary app/web.1:   at Request.emit (events.js:98:17) 
Nov 30 17:28:24 apiary app/web.1:   at Request.<anonymous> (/app/node_modules/request/request.js:1035:10) 
Nov 30 17:28:24 apiary app/web.1:   at Request.emit (events.js:117:20) 
Nov 30 17:28:24 apiary app/web.1:   at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:962:12) 
Nov 30 17:28:24 apiary app/web.1:   at IncomingMessage.emit (events.js:117:20) 
Nov 30 17:28:24 apiary app/web.1:   at IncomingMessage.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:157:28) 
Nov 30 17:28:24 apiary app/web.1:   at IncomingMessage.wrappedEmit [as emit] (/app/node_modules/newrelic/lib/transaction/tracer/index.js:197:46) 
Nov 30 17:28:24 apiary app/web.1:   at _stream_readable.js:944:16 
Nov 30 17:28:24 apiary app/web.1:   at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:157:28) 
Nov 30 17:28:24 apiary app/web.1:   at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:157:28) 
Nov 30 17:28:24 apiary app/web.1:   at process._tickDomainCallback (node.js:492:13) 
Nov 30 17:28:24 apiary app/web.1:   at process.wrappedFunction (/app/node_modules/newrelic/lib/transaction/tracer/index.js:262:51) 
```

### PR DESCRIPTION
**Pull request by freaz**
This also should resolve #17 

After we should bump a version and publish it to registry. When done needs to be updated in core app.

### CODE REVIEW

File: test/refract-parse-with-sourcemaps-test.coffee [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+        .content()
+        .find({element: 'category', meta: {classes: ['api']}})
+        .value()
+    )
+
+    it('Transformation does not throw any exception', ->
+      assert.doesNotThrow(-> refractAdapter.transformAst(apiDescriptionElement))
+    )
+  )
+)
```
Comment (honzajavorek) [inline test/refract-parse-with-sourcemaps-test.coffee:21]: Some of these tests are getting less and less readable in means of understanding what do they test.

```
Transformations • Refract / Parse result with source maps / Transformation does not throw any exception
```

What does it test? What does it mean? Is it something like "metamorphoses do not blow up when fed with Refract containing sourcemaps"?

Comment (freaz) [inline test/refract-parse-with-sourcemaps-test.coffee:21]: > metamorphoses do not blow up when fed with Refract containing sourcemaps

yes exactly that.

Comment (freaz) [inline test/refract-parse-with-sourcemaps-test.coffee:21]: Shall I rename `Transformation does not throw any exception` to `don't blow up` ?
